### ISSUE TITLE
add pyproj to environment.yml

### ISSUE THREAD

**Issue by bregeon** [gammasim/telescope-layouts#3]
```
[(telescopes) [bregeon@lpsc1224x telescope-layouts]$ python ./print_layout.py --layout_list=data/layouts_south.yaml data/telescope_positions_south.ecsv
Traceback (most recent call last):
  File "./print_layout.py", line 9, in <module>
    import layout_array
  File "/ams/bregeon/CTA/Pipeline/ctasoft/telescope-layouts/layout_array.py", line 9, in <module>
    import pyproj
ModuleNotFoundError: No module named 'pyproj'
]
```

**Comment by GernotMaier** [comment]
Added pyproj to the environment file (commit bece12f)

(weird - I didn't find it on conda a few months ago..)
